import React from 'react';

const MainPage = () => {
	return (
		<div>
			Mawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtin
		</div>
	);
};

export default MainPage;