import React from 'react';

const AboutPage = () => {
	return (
		<div>
			Aboutawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtinawdaefarwgergrtghrtin
		</div>
	);
};

export default AboutPage;